name: PR label

permissions:
  pull-requests: read

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  semver-label-check:
    name: Semantic version label check
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check for Semantic Version label
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          echo "Labels on this PR: $LABELS"
          if echo "$LABELS" | grep -qE '⚠️ semver/major|🆕 semver/minor|🔨 semver/patch|semver/none'; then
            echo "✅ Found a semver label"
          else
            echo "::error::PR must have one of the semver labels: ⚠️ semver/major, 🆕 semver/minor, 🔨 semver/patch, semver/none"
            exit 1
          fi
